#pragma once

#include "entity/core/Types.hpp"
#include "entity/components/AnimatedProperties.hpp"
#include "entity/components/Clip.hpp"
#include "entity/components/Layer.hpp"
#include "entity/components/MediaLayer.hpp"
#include "entity/components/Transform.hpp"
#include "entity/timeline/CueTag.hpp"
#include <entt/entt.hpp>
#include <array>
#include <vector>
#include <string>
#include <functional>
#include <optional>
#include <unordered_set>
#include <cmath>
#include <atomic>
#include <cstddef>
#include <cstdint>

namespace entity {

// Callback for when a new clip is created (split, duplicate)
// Parameters: new clip entity, source clip filepath
using ClipCreatedCallback = std::function<void(entt::entity, const std::string&)>;

/**
 * PlaybackState - Current state of timeline playback
 */
enum class PlaybackState {
    Stopped,
    Playing,
    Paused
};

/**
 * Timeline - Manages timeline state, tracks, and playback
 *
 * The Timeline class manages:
 * - Current playback position and state
 * - List of track entities (stored in ECS with TimelineTrack component)
 * - Timeline duration and frame rate
 * - Playback control (play, pause, stop, seek)
 *
 * This is a non-ECS class that works alongside the ECS registry.
 * Tracks are represented as entities with TimelineTrack components.
 */
class Timeline {
public:
    Timeline(entt::registry& registry);
    ~Timeline() = default;

    // Non-copyable
    Timeline(const Timeline&) = delete;
    Timeline& operator=(const Timeline&) = delete;

    /**
     * Update timeline (should be called every frame).
     * Advances current time if playing.
     * @param deltaTime Time elapsed since last frame (seconds)
     */
    void update(double deltaTime);

    // Playback control
    void play();
    void pause();
    void stop();
    void seek(Timecode time);

    // Time getters
    Timecode getCurrentTime() const { return m_currentTime.load(std::memory_order_relaxed); }
    Timecode getDuration() const { return m_duration; }
    PlaybackState getPlaybackState() const { return m_playbackState.load(); }
    double getFrameRate() const { return m_frameRate; }

    // Scrubbing mode - when true, DecodeSystem won't trigger seeks (prevents buffer thrashing)
    void setScrubbing(bool scrubbing) { m_isScrubbing.store(scrubbing); }
    bool isScrubbing() const { return m_isScrubbing.load(); }

    /**
     * Convert a frame number to a Timecode (microseconds).
     * Uses std::round so seekToFrame(N) -> getCurrentFrame() round-trips to N.
     */
    Timecode frameToTime(FrameNumber frame) const {
        return static_cast<Timecode>(std::round((frame / m_frameRate) * 1000000.0));
    }

    /**
     * Convert a Timecode (microseconds) to a frame number.
     * Rounds to nearest. Single source of truth for time->frame across the app.
     */
    FrameNumber timeToFrame(Timecode time) const {
        return static_cast<FrameNumber>(std::round((time / 1000000.0) * m_frameRate));
    }

    /**
     * Get current frame number based on timeline position.
     */
    FrameNumber getCurrentFrame() const { return timeToFrame(getCurrentTime()); }

    /**
     * Seek to a specific integer frame. Round-trip safe with getCurrentFrame().
     */
    void seekToFrame(FrameNumber frame) { seek(frameToTime(frame)); }

    // Time setters
    void setDuration(Timecode duration) { m_duration = duration; }
    void setFrameRate(double frameRate) { m_frameRate = frameRate; }

    // Track management
    entt::entity createTrack(const std::string& name);
    void deleteTrack(entt::entity track);
    const std::vector<entt::entity>& getTracks() const { return m_tracks; }
    size_t getTrackCount() const { return m_tracks.size(); }

    /**
     * Clear all tracks and clips from the timeline.
     * Used when loading a new project.
     */
    void clear();

    /**
     * Delete a clip from its track.
     * Removes clip from track's clip list and destroys the entity.
     */
    void deleteClip(entt::entity clipEntity);

    // ============================================================================
    // Delete-clip undo support. DeleteClipCommand captures the snapshot before
    // destroying the entity, then restores it via restoreDeletedClip on undo.
    // FFmpeg context pointers and GPU descriptor slots are deliberately NOT
    // captured -- they're regenerated by the clip-created callback (decoder
    // open + slot provision), so a restored clip gets a fresh entity ID and
    // fresh resources but identical user-visible state.
    // ============================================================================
    struct DeletedClipSnapshot {
        entt::entity trackEntity{entt::null};

        // Clip data (FFmpeg pointers excluded -- restored entity opens its own).
        std::string     filepath;
        MediaType       mediaType{MediaType::Unknown};
        FrameNumber     startFrame{0};
        FrameNumber     duration{0};
        FrameNumber     mediaStartFrame{0};
        FrameNumber     mediaOutFrame{-1};
        FrameNumber     totalMediaFrames{0};
        double          framerate{30.0};
        PlaybackMode    playbackMode{PlaybackMode::Freeze};
        SectionBehavior sectionBehavior{SectionBehavior::Normal};
        uint32_t        width{0};
        uint32_t        height{0};
        bool            hasAlpha{false};
        bool            frameBlending{false};
        entt::entity    targetScreen{entt::null};

        // Auxiliary components -- absence flag plus by-value snapshot.
        bool               hadTransform{false};
        Transform          transform{};
        bool               hadMediaLayer{false};
        MediaLayer         mediaLayer{};
        bool               hadVideoTexture{false};
        uint32_t           videoTexWidth{0};
        uint32_t           videoTexHeight{0};
        bool               hadFrameBuffer{false};
        bool               hadAnimatedProperties{false};
        AnimatedProperties animatedProperties{};

        bool valid() const { return trackEntity != entt::null; }
    };

    /** Capture every piece of state restoreDeletedClip will need. Returns an
     *  invalid snapshot (trackEntity == entt::null) if the clip can't be
     *  located (no Clip component, or not in any track). */
    DeletedClipSnapshot snapshotClipForDelete(entt::entity clipEntity) const;

    /** Re-create a clip from a snapshot. Allocates a fresh entity (the
     *  original entt::entity is gone), re-emplaces the captured components,
     *  inserts into the original track in start-frame order, and fires the
     *  clip-created callback so the Engine reattaches decoder + GPU
     *  resources. Returns the new entity, or entt::null if the original
     *  track is gone (project reload, track deletion -- callers should
     *  expect this and the undo stack is cleared on project load anyway). */
    entt::entity restoreDeletedClip(const DeletedClipSnapshot& snapshot);

    /**
     * Split a clip at the given frame.
     * Creates a new clip for the portion after the split point.
     * @param clipEntity The clip to split
     * @param splitFrame The frame number to split at (relative to timeline)
     * @return The new clip entity (right side), or entt::null if split failed
     */
    entt::entity splitClip(entt::entity clipEntity, FrameNumber splitFrame);

    /**
     * Duplicate a clip.
     * Creates a copy positioned immediately after the original.
     * @param clipEntity The clip to duplicate
     * @return The new clip entity, or entt::null if duplication failed
     */
    entt::entity duplicateClip(entt::entity clipEntity);

    /**
     * Find which track contains a clip.
     * @return Track entity containing the clip, or entt::null if not found
     */
    entt::entity findTrackForClip(entt::entity clipEntity) const;

    /**
     * Mirror Clip::startFrame / Clip::duration onto the entity's Layer component.
     * Called any time clip placement changes (split, duplicate, drag, trim, load).
     * No-op if the entity has no Layer component (pre-migration or non-clip entity).
     */
    static void syncLayerFromClip(entt::registry& registry, entt::entity entity);

    /**
     * Move a clip from one track to another.
     * @param clipEntity The clip to move
     * @param newTrackIndex The target track index
     * @return True if move was successful
     */
    bool moveClipToTrack(entt::entity clipEntity, int newTrackIndex);

    // ============================================================================
    // Ripple time edits (Phase C #4) — undoable via the captured records below.
    // Helpers operate directly on the registry so they can be unit-tested
    // without spinning up an Engine; the matching Commands wrap these and
    // own the captured-state vectors for undo.
    // ============================================================================

    struct ClipShiftRecord {
        entt::entity entity{entt::null};
        FrameNumber oldStartFrame{0};
    };
    struct ClipSplitRecord {
        entt::entity originalEntity{entt::null};
        FrameNumber oldDuration{0};
        bool hadAnimProps{false};
        AnimatedProperties oldAnimProps{};
        entt::entity newRightEntity{entt::null};
    };
    struct RippleInsertResult {
        bool success{false};
        std::vector<ClipShiftRecord> shifted;
        std::vector<ClipSplitRecord> splits;
    };
    struct RippleDeleteResult {
        bool success{false};
        std::vector<ClipShiftRecord> shifted;
    };

    /**
     * Insert `durationFrames` of empty time at `insertFrame`. Splits any clip
     * that spans `insertFrame` and shifts every clip starting at or after
     * `insertFrame` by `+durationFrames`. Capture the returned record to undo.
     */
    RippleInsertResult rippleInsertTime(FrameNumber insertFrame, FrameNumber durationFrames);
    void undoRippleInsertTime(RippleInsertResult& record);

    /**
     * Delete the time span `[rangeStart, rangeEnd)` from every track. v1
     * limitation: refuses if any clip overlaps the range — caller must split
     * or move overlapping clips first. Clips entirely after the range shift
     * left by `(rangeEnd - rangeStart)`. Capture the returned record to undo.
     */
    RippleDeleteResult rippleDeleteTime(FrameNumber rangeStart, FrameNumber rangeEnd);
    void undoRippleDeleteTime(RippleDeleteResult& record);

    // Get registry reference
    entt::registry& getRegistry() { return m_registry; }
    const entt::registry& getRegistry() const { return m_registry; }

    // ============================================================================
    // Section break points (Phase B refactor of the original Phase C #5 region
    // type). Sections are now point markers that split the timeline into
    // contiguous spans -- span N is `[breaks[N].breakFrame, breaks[N+1].breakFrame)`
    // (or to the end of the timeline after the last break). The vector is kept
    // sorted ascending by `breakFrame`. `fadeSeconds` is serialized now;
    // Phase D activates it as the auto-fade envelope around boundary clips.
    // ============================================================================
    struct Section {
        Timecode    breakFrame{0};      // Single point on the timeline (microseconds)
        uint32_t    color{0xFF6090C8};  // ImU32 (ABGR), default cool blue
        double      fadeSeconds{0.0};   // Phase D will use; serialized now
    };

    const std::vector<Section>& getSections() const { return m_sections; }

    /** Insert a section break at the given frame. Returns false if a break
     *  already exists at that exact frame. Sorted-insert; no snapping
     *  (callers snap to the tick grid before invoking). */
    bool addSectionBreak(Timecode breakFrame,
                         uint32_t color = 0xFF6090C8, double fadeSeconds = 0.0);

    /** Remove the break at `breakFrame`. Returns true on success. */
    bool removeSectionBreak(Timecode breakFrame);

    /** Edit an existing break. If `newBreakFrame != oldBreakFrame`, fails when
     *  another break already sits at `newBreakFrame`. Re-sorts on change. */
    bool editSectionBreak(Timecode oldBreakFrame, Timecode newBreakFrame,
                          uint32_t newColor, double newFadeSeconds);

    /** Look up the first break strictly after `time`. Binary search (hot path
     *  called every tick by SectionScheduler). nullptr if none. */
    const Section* findNextBreakAfter(Timecode time) const;

    /** Find a break within ±tolerance microseconds of `time`. Used by the
     *  ruler hit-test for right-click on a break line. nullptr if none. */
    const Section* findSectionBreakNear(Timecode time, Timecode tolerance) const;

    /** Drop every section. Used by Timeline::clear() and the project loader. */
    void clearSections() { m_sections.clear(); }

    /** True when the SectionScheduler has parked the playhead at a break this
     *  tick. UI uses this for spacebar dispatch + playhead visual feedback;
     *  Engine reads it before enqueueing TogglePlayPause vs SectionGo. */
    bool sectionAtBreak() const { return m_atSectionBreak.load(); }
    void setSectionAtBreak(bool v) { m_atSectionBreak.store(v); }

    // Section-break selection — mutually exclusive with clip/screen/projector/cue
    // (mirrors the cue-selection slot from Phase A). Setting a break clears the
    // others; setting any of the others clears this. Selection is stored by
    // breakFrame because vector indices shift across edits.
    void setSelectedSectionBreak(std::optional<Timecode> breakFrame) {
        m_selectedSectionBreakFrame = breakFrame;
        if (breakFrame.has_value()) {
            m_selectedClip = entt::null;
            m_selectedScreen = entt::null;
            m_selectedProjector = entt::null;
            m_selectedProp = entt::null;
            m_selectedCueNumber.reset();
        }
    }
    std::optional<Timecode> getSelectedSectionBreak() const {
        return m_selectedSectionBreakFrame;
    }

    // ============================================================================
    // Cue tags — numbered timeline markers fired by command to seek-and-play.
    // Sorted ascending by `number`; uniqueness enforced on insert/edit.
    // ============================================================================
    const std::vector<CueTag>& getCueTags() const { return m_cueTags; }

    /** Insert a cue. Returns false if a cue with the same `number` already
     *  exists (no-op in that case). Sorted insert via lower_bound. */
    bool addCueTag(CueTag tag);

    /** Remove the cue with the given number. Returns true if a cue was
     *  removed. */
    bool removeCueTag(double number);

    /** Look up a cue by number. Returns nullptr if absent. */
    const CueTag* findCueTag(double number) const;

    /** Edit an existing cue. If `newNumber != oldNumber`, fails when
     *  another cue already uses `newNumber`. Re-sorts the vector if the
     *  number changed. Returns true on success. */
    bool editCueTag(double oldNumber, double newNumber,
                    Timecode newTimestamp, std::string newLabel);

    /** Drop every cue. Used by Timeline::clear() and the project loader. */
    void clearCueTags() { m_cueTags.clear(); }

    // Selection management
    void setSelectedClip(entt::entity clip) {
        m_selectedClip = clip;
        if (clip != entt::null) {
            m_selectedCueNumber.reset();
            m_selectedSectionBreakFrame.reset();
            // Clip selection doesn't fight with prop selection in the same way
            // it doesn't fight with screen/projector — we keep all four slots
            // independent so the user can have a clip and a prop selected at
            // once if they want to compare. The mutual exclusion is between
            // *stage* primitives (screen/projector/prop) only.
        }
    }
    entt::entity getSelectedClip() const { return m_selectedClip; }

    void setSelectedScreen(entt::entity screen) {
        m_selectedScreen = screen;
        m_selectedProjector = entt::null;
        m_selectedProp = entt::null;
        if (screen != entt::null) {
            m_selectedCueNumber.reset();
            m_selectedSectionBreakFrame.reset();
        }
    }
    entt::entity getSelectedScreen() const { return m_selectedScreen; }

    void setSelectedProjector(entt::entity projector) {
        m_selectedProjector = projector;
        m_selectedScreen = entt::null;
        m_selectedProp = entt::null;
        if (projector != entt::null) {
            m_selectedCueNumber.reset();
            m_selectedSectionBreakFrame.reset();
        }
    }
    entt::entity getSelectedProjector() const { return m_selectedProjector; }

    // Prop selection — mutually exclusive with screen/projector. Props are
    // pre-vis-only stage geometry (see Prop.hpp); selecting one drives the
    // PropsWindow highlight, the 3D stage view's selection wireframe, and
    // the PropertyWindow's prop pane.
    void setSelectedProp(entt::entity prop) {
        m_selectedProp = prop;
        m_selectedScreen = entt::null;
        m_selectedProjector = entt::null;
        if (prop != entt::null) {
            m_selectedCueNumber.reset();
            m_selectedSectionBreakFrame.reset();
        }
    }
    entt::entity getSelectedProp() const { return m_selectedProp; }

    // Cue selection — mutually exclusive with clip/screen/projector/section.
    // Setting a cue clears the others; setting any of the others clears this.
    void setSelectedCueNumber(std::optional<double> number) {
        m_selectedCueNumber = number;
        if (number.has_value()) {
            m_selectedClip = entt::null;
            m_selectedScreen = entt::null;
            m_selectedProjector = entt::null;
            m_selectedProp = entt::null;
            m_selectedSectionBreakFrame.reset();
        }
    }
    std::optional<double> getSelectedCueNumber() const { return m_selectedCueNumber; }

    // Clear all selection (deselect clip, screen, projector, cue, section break)
    void clearSelection() {
        m_selectedClip = entt::null;
        m_selectedScreen = entt::null;
        m_selectedProjector = entt::null;
        m_selectedProp = entt::null;
        m_selectedCueNumber.reset();
        m_selectedSectionBreakFrame.reset();
    }

    // Expansion state (for twirl-down property tracks)
    void setTrackExpanded(entt::entity track, bool expanded) {
        if (expanded) {
            m_expandedTracks.insert(static_cast<uint32_t>(track));
        } else {
            m_expandedTracks.erase(static_cast<uint32_t>(track));
        }
    }
    bool isTrackExpanded(entt::entity track) const {
        return m_expandedTracks.count(static_cast<uint32_t>(track)) > 0;
    }
    void setClipExpanded(entt::entity clip, bool expanded) {
        if (expanded) {
            m_expandedClips.insert(static_cast<uint32_t>(clip));
        } else {
            m_expandedClips.erase(static_cast<uint32_t>(clip));
        }
    }
    bool isClipExpanded(entt::entity clip) const {
        return m_expandedClips.count(static_cast<uint32_t>(clip)) > 0;
    }

    /**
     * Set callback for when new clips are created (split, duplicate).
     * Engine uses this to create decoders and GPU resources.
     */
    void setClipCreatedCallback(ClipCreatedCallback callback) { m_clipCreatedCallback = callback; }

private:
    entt::registry& m_registry;

    // Timeline state. m_currentTime is atomic so the show thread can read it
    // (via getCurrentTime() / getCurrentFrame()) for buildRenderFrame /
    // buildSceneSnapshot while the editor thread mutates it via update() /
    // seek() / play()/pause()/stop(). All writes happen on the editor thread.
    std::atomic<Timecode> m_currentTime{0};
    Timecode m_duration{600000000};  // Default: 10 minutes = 600 seconds = 600,000,000 microseconds
    std::atomic<PlaybackState> m_playbackState{PlaybackState::Stopped};
    std::atomic<bool> m_isScrubbing{false};  // True during drag-scrubbing (prevents decoder seeks)
    double m_frameRate{30.0};

    // Track entities (stored in ECS)
    std::vector<entt::entity> m_tracks;

    // Named time-range sections, persisted in project files.
    std::vector<Section> m_sections;

    // Numbered cue markers, sorted ascending by `number`. Persisted at v9.
    std::vector<CueTag> m_cueTags;

    // Selection state
    entt::entity m_selectedClip{entt::null};
    entt::entity m_selectedScreen{entt::null};
    entt::entity m_selectedProjector{entt::null};
    entt::entity m_selectedProp{entt::null};
    std::optional<double> m_selectedCueNumber;
    // Section breaks are identified by their breakFrame because vector
    // indices shift across edits and break entries don't have a stable
    // identifier other than their position in time.
    std::optional<Timecode> m_selectedSectionBreakFrame;
    std::unordered_set<uint32_t> m_expandedTracks;
    std::unordered_set<uint32_t> m_expandedClips;

    // Set by SectionScheduler when the playhead has just been parked at a
    // break this tick. Atomic so UI/keyboard threads can read coherently.
    std::atomic<bool> m_atSectionBreak{false};

    // Callback for clip creation
    ClipCreatedCallback m_clipCreatedCallback;
};

// ============================================================================
// Section color palette (Round-3 Phase 2 — auto-coloring).
// 8-entry ABGR palette. The implicit first segment uses index 0; UI-driven
// adds index by `getSections().size() + 1` so the first user-added break
// gets palette[1] and successive breaks rotate through the palette.
// `addSectionBreak` keeps its blue default for backward-compat with
// serialized projects + scripted creation; the UI add path passes a
// palette-derived color explicitly.
// ============================================================================
namespace sectionPalette {

inline constexpr std::array<uint32_t, 8> kSectionColors = {
    0xFF6090C8u,  // cool blue (matches addSectionBreak default)
    0xFFE07A7Au,  // coral
    0xFF7AC07Au,  // jade green
    0xFFD0A050u,  // amber
    0xFF9870C0u,  // violet
    0xFF50B0C0u,  // teal
    0xFFC07AA0u,  // rose
    0xFF80A050u,  // olive
};

inline uint32_t pickColor(std::size_t index) {
    return kSectionColors[index % kSectionColors.size()];
}

} // namespace sectionPalette

} // namespace entity
